package kylekewley.garagedooropener.protocolbuffers;// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .//GarageCommand.proto
import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class GarageCommand extends Message {

  public static final Command DEFAULT_COMMAND = Command.TRIGGER_DOOR;
  public static final Integer DEFAULT_GARAGEID = 0;

  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final Command command;

  @ProtoField(tag = 2, type = UINT32, label = REQUIRED)
  public final Integer garageId;

  public GarageCommand(Command command, Integer garageId) {
    this.command = command;
    this.garageId = garageId;
  }

  private GarageCommand(Builder builder) {
    this(builder.command, builder.garageId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GarageCommand)) return false;
    GarageCommand o = (GarageCommand) other;
    return equals(command, o.command)
        && equals(garageId, o.garageId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = command != null ? command.hashCode() : 0;
      result = result * 37 + (garageId != null ? garageId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GarageCommand> {

    public Command command;
    public Integer garageId;

    public Builder() {
    }

    public Builder(GarageCommand message) {
      super(message);
      if (message == null) return;
      this.command = message.command;
      this.garageId = message.garageId;
    }

    public Builder command(Command command) {
      this.command = command;
      return this;
    }

    public Builder garageId(Integer garageId) {
      this.garageId = garageId;
      return this;
    }

    @Override
    public GarageCommand build() {
      checkRequiredFields();
      return new GarageCommand(this);
    }
  }

  public enum Command
      implements ProtoEnum {
    TRIGGER_DOOR(1);

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
