package kylekewley.garagedooropener.protocolbuffers;

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Programming/C++/GarageServer/ProtocolBuffers/GarageMetaData.proto
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class GarageMetaData extends Message {

  public static final Integer DEFAULT_DOORCOUNT = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer doorCount;

  public GarageMetaData(Integer doorCount) {
    this.doorCount = doorCount;
  }

  private GarageMetaData(Builder builder) {
    this(builder.doorCount);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GarageMetaData)) return false;
    return equals(doorCount, ((GarageMetaData) other).doorCount);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = doorCount != null ? doorCount.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<GarageMetaData> {

    public Integer doorCount;

    public Builder() {
    }

    public Builder(GarageMetaData message) {
      super(message);
      if (message == null) return;
      this.doorCount = message.doorCount;
    }

    public Builder doorCount(Integer doorCount) {
      this.doorCount = doorCount;
      return this;
    }

    @Override
    public GarageMetaData build() {
      return new GarageMetaData(this);
    }
  }
}
